import './search-events-page.html';
import './search-events-page.css';
import './search-events-page.js';
import './search-friends-page.html';
import './search-friends-page.css';
import './search-friends-page.js';
import './event-page.css';
import './event-page.html';
import './event-page.js';
